### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by gkasprow** [flisadam/RFID_system#2]
- [x] please remove all project -specific libraries. Install them as global. Now when I open the project it complains about missing libs.
- [x] add differential pair directive Place->Directie -> diff pairs
- [x] what is the role of P1 connector? Why there is same designator for both connectors?
- [x] don't use regular L with ceramic capacitor as filter. Use ferrite bead instead, otherwise it will oscillate.
- [x] fix this
![obraz](https://user-images.githubusercontent.com/4325054/33101933-bc3ae74e-cf1a-11e7-9a47-a168d7da5589.png)
- [x] there is serious error in USB connector grounding. Check it with application note. TVS GND should go to circuit GND!
- [x] RFID receivers must be synchronized together to not interfere with other channels. All RFID coils must have the same phase and frequency. Individual crystals don't provide such functionality.
- [x] SS line is not connected to the sheet entry

**Comment by flisadam** [comment]
1 I removed libraries. It should not complains now.

2 I added diff pair to USB D+ D- data.

3 I intented to use P1 as a switch on-off each CPU-slave and master with jumpers. 

5  I changed it. Hope it is more readable now.



6 I took connection of TVS to USB from that manual : 
Atmel AVR1017: XMEGA - USB Hardware
Design Recommendations page 8
http://www.atmel.com/images/doc8388.pdf
![usbconnection](https://user-images.githubusercontent.com/33846689/33140659-e56b8358-cfb0-11e7-8f7c-f80bcb418fa3.png)


7. Still to do.
8. I get a little bit confused about this. When i compile only Master.SchDoc- the message window returns error's of only one pin's connection 
![pin](https://user-images.githubusercontent.com/33846689/33141029-20759c58-cfb2-11e7-97d1-c5002e4751d4.png)
On the other hand when I compile hole project- there are none errors-just warnings about multiply name nets:
![nets](https://user-images.githubusercontent.com/33846689/33141214-b9c39284-cfb2-11e7-9987-244bc4fb629c.png)
Finally when i check connection on the pcb everythink looks fine- I can connect with autoRoute each Slave SS pin in SS_bus with Xmega pins and also antenna bus
![track](https://user-images.githubusercontent.com/33846689/33141422-60274184-cfb3-11e7-96fc-daa1866b4b8e.png)

**Comment by gkasprow** [comment]
6. Such USB TVS protection makes sense if you have metal enclosure with metallic panel that is connected with PE terminal. In such cases the ESD current flows to the chassis. We supply it from USB so these components are not needed and GND can be shorted with USB connector.
8. OK, it is fine, in my case for some reason Alt+click does not work.

In case of synchronization, you'd better visit biologists lab and see how it is done on prototype. It simply works and I don't remember how I did it :)

**Comment by flisadam** [comment]
I changed the TVS connection-USB shield is shorted with GND ,TVS diode GND is also connected to GND.
I also add ferrite bead instead of L (I could not find any of them in Cern lib- I changed description of element and added footprint 0603 from other component)
https://www.tme.eu/gb/details/blm18he152sn1d/ferrite-beads/murata/


About the case of synchronization, could You send me via mail information with adress and person I can contact to visit biologist lab and see your prototype?

**Comment by flisadam** [comment]
It seems that all of problem's in this issue were solved. Anyway, Could You verify the last version?
