### ISSUE TITLE
RFID reader with autheitification

### ISSUE THREAD

**Issue by gkasprow** [flisadam/RFID_system#3]
It seem we have to change the reader chip.
HTRC110 has synchronisation and was used in original experiment.
It reads animal tags

**Comment by gkasprow** [comment]
to synchronize the ICs simply connect them as on the photo 
https://drive.google.com/file/d/11MaUKYV9UiBc9bnIUfT4B7IjpPNTmtSM/view

**Comment by flisadam** [comment]
I have some questions about synchronizing

1.  Do I need to connect only pin  XTAL1 first one with XTAL2 second one and XTAL 2 second one with XTAL1 first one? 

2. This synchronization concerns only the pair of ICs? So now I have 4 pairs, in which ICs are synchronised or do I have to connect 8 ICs with each other?

3. According to datasheet the pin MODE can active digital filter on DIN line - do we need it ?

4. This modules requires 2-way communication with ATtiny.  In my solution ATtiny is powered with 3V3 and HTRC110 with 5V. So in case of  communication on lines DIN, SCK and DOUT do i need to use converation of logic states (5V0->3V3; 3V3->5V)?

**Comment by gkasprow** [comment]
> I have some questions about synchronizing
> 
> 1.  Do I need to connect only pin  XTAL1 first one with XTAL2 second one and XTAL 2 second one with XTAL1 first one? 
no, just give common clock oscillator and connect to all inputs
> 
> 2. This synchronization concerns only the pair of ICs? So now I have 4 pairs, in which ICs are synchronised or do I have to connect 8 ICs with each other?
they all need to be kept in sync

> 
> 3. According to datasheet the pin MODE can active digital filter on DIN line - do we need it ?
I'd provide such option 

> 4. This modules requires 2-way communication with ATtiny.  In my solution ATtiny is powered with 3V3 and HTRC110 with 5V. So in case of  communication on lines DIN, SCK and DOUT do i need to use converation of logic states (5V0->3V3; 3V3->5V)?

What are logic levels? Is 3.3V logic H of HTRC chip? 5V->3.3V translation is simple and resistive divider does the job for such frequency
> 
> 
>

**Comment by flisadam** [comment]
I have commited updated scheamtics with new RFID reader. Could You verify it?

I have also question if we can also use only one oscillator directly(or maybe through some bufor) to timing all Attiny's?
8 separate clock's does not seem to be much optimalized
I have never done system with several CPU's, so I'm not sure if it will work properly.

**Comment by gkasprow** [comment]
Sure, that's the way to go. The same clock signal can drive attiny and RFID chip.

**Comment by flisadam** [comment]
I have added common clock for slaves and ICS.

**Comment by gkasprow** [comment]
This won't work. Use single clock generator and distribute it to all clock inputs.
Crystal oscillator will work only with single input and single output.
In current project version multiple outputs are connected together!!!

**Comment by gkasprow** [comment]
- [x] Please get rid of P1. This adds inductance to the supply nets. Take into account that AVCC is supplied continuously.
- [x] missing SCK pulldown
- [x] please make sure that you connected right SPI pins to the ISP connector. Different Atmega/ATtiny have different assignment. Some use RxD/TxD pins, some SPI pins.
- [ ] use right-angled LEDs and place them close to the side panels. For channel LEDs, place them close to the BNC connectors.

**Comment by flisadam** [comment]
According to Attiny 441 datasheet pins need to programming is P4, P5 ,P6.
![attiny_prog](https://user-images.githubusercontent.com/33846689/33966433-dd41ef22-e05f-11e7-8e83-2e51abd811aa.png)

**Comment by flisadam** [comment]
I added two front x4 Green Leds. Regarding to diodes which will be in side panels. I looked into 2x right angled diodes ( I have 2 diodes in each slave CPU) and most diodes cost about 7-8 zl. For 8-CPU's it will cost about 50zł  Use it anyway? 

Link to the store 
https://pl.mouser.com/ProductDetail/Dialight/553-0111-200F/?qs=sGAEpiMZZMtilyJihmhKq5X4S%2F1HbqhdPu9VS9%252b4wuY%3D

**Comment by gkasprow** [comment]
We need two SPI ports.
One master to read the HTRC110, one slave to give access to the main CPU.
But the Attiny has only one hardware SPI port
I assume that you want to read the RFID chip using software SPI

We don't need more than 1 LED per channel so 2x quad LED is fine.
The BNCs you used have shorten grounds of lower and upper connectors. It is not written in the datasheet but I have them in the lab.
So they cannot be used in such application.

Let's replace them with something more suitable.
There are ones with identical footprint, I use them in 
https://github.com/m-labs/sinara/tree/master/ARTIQ_ALTIUM/EEMs/Sampler
Just take this design and copy footprint and schematic symbols.

**Comment by flisadam** [comment]
I changed BNC's.
I left 2x quad led on the front panel, but i would like to left 1-2 usual SMD diodes to each slave CPU. It will help me with programming

**Comment by gkasprow** [comment]
OK, go on with layout.
