### ISSUE TITLE
PCB layout and routing

### ISSUE THREAD

**Issue by flisadam** [flisadam/RFID_system#5]
I have do peliminary placement of components and routing in slave circuits. Before I proceed to master circuiut and connection beetwen master-slave, I wanted to know if you have some comments. Could you look at it?

Strings S1-S8 are temporary, just for me to easier look at PCB.
I will  correct some tracks to connect pads at 90 degree in next commit.

**Comment by gkasprow** [comment]
go on with routing.
Use mainly top layer, bottom will be solid ground plane. Max 1cm traces are allowed there.
use 0.3/0.6 vias for regular traces, 0.8/0.6 vias for power traces, >6 mils traces and 6 mils clearace for regular tracks, >20 mils for power traces.

**Comment by flisadam** [comment]
I just commited last changes. I route all tracks, but honestly it could be done much better.  I think there are too many vias and bottom layer routes.  Could you look also on diff USB pair tracks? Becouse of usb footprint i could not place them closer, so i make longer   D_P trace to equals impednaces. Was it neccesery?
How do you think? Can I put ground polygon and make GND connection or try again to route it better?

**Comment by gkasprow** [comment]
As I wrote, don't use that long traces on bottom side. It must be solid plane!
There is plenty of space on top side. Vias do not cost any money.
for this speed U don't need to equalize USB traces
here is example of 2-layer routing.
please note:
- vias at the board edge
- max trace length at the ground plane
- 15mils distance between polygon and traces
- pieces of GND polygon connected with solid GND polygon using vias

![obraz](https://user-images.githubusercontent.com/4325054/34921106-e2b633d2-f97d-11e7-8107-277908c7b372.png)
![obraz](https://user-images.githubusercontent.com/4325054/34921110-eb5316fe-f97d-11e7-9998-d630f982b337.png)

**Comment by flisadam** [comment]
I commited PCB with corrected bottom traces-all of them are shorter than 1cm now. If you have a while, you can look at it. In meantime I will make same cosmetic changes and add GND polygon

**Comment by flisadam** [comment]
I uploaded full PCB layout. Do you have any suggestions or comments ?

**Comment by gkasprow** [comment]
that's OK,
I fixed some minor issues and will ship it to the assembly house.
